### ISSUE TITLE
Probability of selecting 'Burger King'

### ISSUE THREAD

**Issue by rmhartog** [anandsaw/LunchSelector#1]
Hey guys, I see from the code that it is still possible to select burger king with a probability of 1/64, please fix asap.

**Comment by anandsaw** [comment]
This is being resolved in the current issue

**Comment by anandsaw** [comment]
Also this has been assigned to @VHellendoorn

**Comment by VHellendoorn** [comment]
Thanks @anandsaw, @rmhartog. I worked with this a little and have the current output:
Your place of dining today is: Subway (13%)
The options ranked:
Subway	13%
KFC	13%
Vapiano	12%
La Place	12%
Pizza Hut	12%
McDonald's	12%
Burger King	12%*
Sodexo	11%*
*Disregarded, as we hate these people.

(as an example). If you agree, I will make a PR.

**Comment by anandsaw** [comment]
I think disregarded output should be named and shamed, it shouldnt have just an asterix.

**Comment by rmhartog** [comment]
Thanks @VHellendoorn, that will suffice for now. We will have to improve the algorithm some more as we go along.
